// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmBJ3GqAOU8d0yulTt7FZhIeeqOoR-ko4',
    appId: '1:340194168269:android:f1cfc740f27289fc6e8884',
    messagingSenderId: '340194168269',
    projectId: 'wash-wheels-66ac1',
    storageBucket: 'wash-wheels-66ac1.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABejWDgM0dpa7Yxf5M6Os-UknGPkR_pBg',
    appId: '1:340194168269:web:83964cb880cd064e6e8884',
    messagingSenderId: '340194168269',
    projectId: 'wash-wheels-66ac1',
    authDomain: 'wash-wheels-66ac1.firebaseapp.com',
    storageBucket: 'wash-wheels-66ac1.firebasestorage.app',
    measurementId: 'G-N0LTV580CL',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2cvf_5GGrjVUwFbYyfDx6EnwTA__oIK4',
    appId: '1:340194168269:ios:4313ec05d0927b056e8884',
    messagingSenderId: '340194168269',
    projectId: 'wash-wheels-66ac1',
    storageBucket: 'wash-wheels-66ac1.firebasestorage.app',
    iosClientId: '340194168269-lcd4l8gdcghl7vbg38531ttf8qqk77cp.apps.googleusercontent.com',
    iosBundleId: 'com.example.washWheels',
  );

}